//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackyJavaScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class javascripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal javascripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HackyJavaScript.javascripts", typeof(javascripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Global constants
        ///const DOCKED_IFRAME_ID = &quot;_tableViewFrameDocked&quot;;
        ///const UNDOCKED_IFRAME_ID = &quot;_tableViewFrameUnDocked&quot;;
        ///
        ///
        ////*
        /// * Converts the element&apos;s innerHTML to its innerText
        /// */  
        ///function innerTextToHtml(element) {
        ///    var text = element.innerText;
        ///    element.innerHTML = text;
        ///}
        ///
        ///
        ////*
        /// * Is this string an HTML element? 
        /// */ 
        ///function isHtmlString(s) {
        ///    return s.startsWith(&quot;&lt;&quot;) &amp;&amp; s.endsWith(&quot;&gt;&quot;);
        ///}
        ///
        ///
        ///function getTableFrom(iframeElement) {
        ///    if (iframeElement === null) {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlscript {
            get {
                return ResourceManager.GetString("htmlscript", resourceCulture);
            }
        }
    }
}
